services:
  - type: web
    name: trx-control-bot
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: BOT_TOKEN
        value: 7659505060:AAFmwIDn2OgrtNoemPpmBWaxsIfdsQdZGCI
      - key: CHAT_ID
        value: 7417215529
